### ISSUE TITLE
rdkit-sys

### ISSUE THREAD

**Issue by xrl** [chrissly31415/rdkitcffi#2]
I am on a Mac and I want to support building specific version of RDKit for various platforms (MacOS ARM/Intel, Linux ARM/Intel). So I have under taken a path to easier integration with rdkit-sys, check it out: https://crates.io/crates/rdkit-sys

**Comment by xrl** [comment]
I am going to politely steal your cffi ideas, it's all new to me but I think I can figure out how to get fully cargo-ify it.

**Comment by xrl** [comment]
happy to report I used your code well in the repo. now I have a self-building crate with your very convenient molecule implementation on top of the low level bindings.

**Comment by CHLoschen** [comment]
HI xrl,  I am glad you find the code useful! Actually, I planned (and also started) to have something like an rdkit-sys in order to get rid of the compiled .so in the repo but did not find the time to finish this. Pretty cool that this is now available!

**Comment by chrissly31415** [comment]
Hi xrl, I am glad you find the code useful! Actually, I planned (and also started) to have something like an rdkit-sys in order to get rid of the compiled .so in the repo but did not find the time to finish this. Pretty cool that this is now available!
